export const tracks = [
    {id: 1,
    name: "Guilt",
    trackTitle: "",
    author: "Nero",
    album: "Welcome Reality",
    time: "4:44",
    },
    {id: 2,
    name: "Elektro",
    trackTitle: "",
    author: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    time: "2:22",
    },
    {id: 3,
    name: "I’m Fire",
    trackTitle: "",
    author: "Ali Bakgor",
    album: "I’m Fire",
    time: "2:22",
        },
    {id: 4,
    name: "Non Stop",
    trackTitle: "(Remix)",
    author: "Стоункат, Psychopath",
    album: "Non Stop",
    time: "4:12",
        },        
    {id: 5,
    name: "Run Run",
    trackTitle: "(feat. AR/CO)",
    author: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    time: "2:54",
        },
    {id: 6,
    name: "Eyes on Fire",
    trackTitle: "(Zeds Dead Remix)",
    author: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    time: "5:20",
     },
    {id: 7,
    name: "Mucho Bien",
    trackTitle: "(Hi Profile Remix)",
    author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    time: "3:41",
    },
    {id: 8,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 9,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 10,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 11,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 12,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 13,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 14,
    name: "Knives n Cherries",
    trackTitle: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
    },
    {id: 15,
    name: "How Deep Is Your Love",
    trackTitle: "",
    author: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    time: "3:32",
    },
    {id: 16,
    name: "Morena",
    trackTitle: "",
    author: "Tom Boxer",
    album: "Soundz Made in Romania",
    time: "3:36",
    },
  ]
  