export const PLAY_TRACK = "PLAY_TRACK"
export const PAUSE_TRACK = "PAUSE_TRACK"
export const PREVIOUS_TRACK = "PREVIOUS_TRACK";
export const NEXT_TRACK = "NEXT_TRACK";
export const SHUFFLE_PLAYLIST = "SHUFFLE_PLAYLIST"
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK"
export const ADD_PLAYLIST = "ADD_PLAYLIST"
export const REPEAT_TRACK = "REPEAT_TRACK"
export const PAGE_PLAYLIST = "PAGE_PLAYLIST"

