export const PREVIOUS_TRACK = "PREVIOUS_TRACK";
export const NEXT_TRACK = "NEXT_TRACK";
export const SHUFFLE_PLAYLIST = "SHUFFLE_PLAYLIST"
export const TOGGLE_SHUFFLE = "TOGGLE_SHUFFLE"
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK"
export const ADD_PLAYLIST = "ADD_PLAYLIST"

